---
dependencies:
  - role: evgnomon.catamaran.z_secrets
  - role: evgnomon.catamaran.z_defaults
galaxy_info:
  author: Hamed Ghasemzadeh
  description: Create virtual machines
  license_fil: COPYING
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
        - 8
  categories:
    - devops
    - automation
  tags:
    - defaults
    - configuration
