---
- name: "Check"
  tags:
    - check
  script: check
  args:
    chdir: "{{ workspace }}"

- name: "Build"
  tags:
   - build
  script: build
  args:
    chdir: "{{ workspace }}"

- name: "Smoke"
  tags:
   - smoke
  script: smoke
  args:
    chdir: "{{ workspace }}"
