---
- name: Create A records
  community.general.cloudflare_dns:
    zone: "{{ name_zone }}"
    record: "{{ item.record_name }}"
    type: A
    value: "{{ item.record_ip }}"
    api_token: "{{ api_token }}"
    state: present
    ttl: 300
    proxied: false
  with_items: "{{ z_dns_a_records | default([]) }}"
  no_log: true
