#!/usr/bin/env bash

set -e

if [ -f "go.mod" ]; then
  Z=$(pwd)/dist/z-$(go env GOOS)-$(go env GOARCH)
  $Z smoke

elif [ -f "package.json" ]; then
  echo no smoke

elif [ -f build.zig ]; then
  echo no smoke

elif [ -f "CMakeLists.txt" ]; then
  echo no smoke

elif [ -f "pyproject.toml" ]; then
  echo no smoke

else
  echo "No recognized build configuration found."
  exit 1
fi
