---
galaxy_info:
  author: Hamed Ghasemzadeh
  description: Run a build output as a service on remote hosts
  license_fil: COPYING
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
        - 8
  categories:
    - devops
    - automation
  tags:
    - defaults
    - configuration
dependencies:
  - role: evgnomon.catamaran.z_defaults
  - role: z_lib_var
  - role: z_ca_deploy
  - role: z_install
    vars:
      z_target: "{{ z_service_name }}"
