---
- shell: |
    z deinit -v
    z join -d zygote.run --host {{ inventory_hostname }} --num-shards {{ z_num_shards }} --shard-size {{ z_shard_size }} --db {{ z_user }}
  args:
    chdir: /tmp
  environment:
    ZYGOTE_CONFIG_HOME: "{{ z_backup_dir }}"

