---
- setup:
    gather_subset: min
- set_fact:
    z_os: >-
      {{
        {
          'Darwin': 'darwin',
          'Debian': 'linux',
          'Windows': 'windows'
        }[ansible_os_family] | default('')
      }}
    z_arch: >-
      {{
        {
          'x86_64': 'amd64',
          'aarch64': 'arm64',
          'i386': '386'
        }[ansible_architecture] | default('')
      }}
