---
galaxy_info:
  author: Hamed Ghasemzadeh
  description: Set minimum required Ansible facts
  license_file: COPYING
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
        - 8
  categories:
    - devops
    - automation
  tags:
    - defaults
    - configuration
