namespace: evgnomon
name: catamaran
version: 0.1.3
readme: README.md
authors:
  - Hamed Ghasemzadeh <hg@evgnomon.org>
description: Catamaran Ansible module
license: HGL
tags: [catamaran,github, deops, ansible]
repository: https://github.com/evgnomon/catamaran
