namespace: evgnomon
name: catamaran
version: 0.1.9
readme: README.md
authors:
  - Hamed Ghasemzadeh <hg@evgnomon.org>
description: Catamaran Ansible module
tags: [catamaran,github, deops, ansible]
license_file: COPYING
repository: https://github.com/evgnomon/catamaran
