---
- name: Ensure sysctl.d directory exists
  ansible.builtin.file:
    path: /etc/sysctl.d
    state: directory
    mode: '0755'
  become: true

- name: Deploy sysctl configuration to disable IPv6
  ansible.builtin.template:
    src: 99-disable-ipv6.conf.j2
    dest: /etc/sysctl.d/99-disable-ipv6.conf
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Apply sysctl settings

- name: Apply sysctl settings for IPv6 disablement
  ansible.builtin.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  loop: "{{ disable_ipv6_settings }}"
  become: true
