---
# Default variables that can be overridden
docker_version: "latest"  # Can be set to specific version like "20.10.17"
docker_log_max_size: "10m"
docker_log_max_file: "3"
docker_ulimit_nofile: "1024:4096"
docker_user: "{{ ansible_user | default('admin') }}"
debian_codename: "{{ ansible_distribution_release | default(ansible_lsb.codename | default('bullseye')) }}"
